### ISSUE TITLE
Sporadic "An exception has been encountered."

### ISSUE THREAD

**Issue by jbattermann** [madskristensen/MarkdownEditor#22]
### Installed product versions
- Visual Studio: 2015 Professional (Update 2 & 3.. happened with both)
- This extension: 1.4.102

### Description
When opening a a solution which contains a markdown file that was open before closing VS, re-opening that solution again in VS (and therefore VS also automatically re-opening/displaying the .md file) I get an VS Error like this:

![markdowneditor](https://cloud.githubusercontent.com/assets/828/16544664/94717728-410e-11e6-919c-42bb1bc2ddf4.png)

```
---------------------------
Microsoft Visual Studio
---------------------------
An exception has been encountered. This may be caused by an extension.



You can get more information by examining the file 'C:\Users\joerg\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml'.
---------------------------
OK   
---------------------------
```
 
.. and looking in the ActivityLog.xml, it reveals the following errors:

```xml
  <entry>
    <record>661</record>
    <time>2016/07/03 09:08:29.916</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: length&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)&#x000D;&#x000A;   at MarkdownEditor.MarkdownClassifier.GetClassificationSpans(SnapshotSpan span) in C:\projects\markdowneditor\src\Classifier\MarkdownClassifier.cs:line 64&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__5.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>
  <entry>
    <record>662</record>
    <time>2016/07/03 09:08:29.916</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: length&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)&#x000D;&#x000A;   at MarkdownEditor.MarkdownClassifier.GetClassificationSpans(SnapshotSpan span) in C:\projects\markdowneditor\src\Classifier\MarkdownClassifier.cs:line 64&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__5.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>
  <entry>
    <record>663</record>
    <time>2016/07/03 09:08:29.916</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: length&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)&#x000D;&#x000A;   at MarkdownEditor.MarkdownClassifier.GetClassificationSpans(SnapshotSpan span) in C:\projects\markdowneditor\src\Classifier\MarkdownClassifier.cs:line 64&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__5.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>
```

### Steps to recreate (assuming you have the Markdown Editor Extension installed)
1. [Clone my repository](https://github.com/jbattermann/serilog-sinks-applicationinsights/)
2. Open the `serilog-sinks-applicationinsights.sln` in VS and in it, open the 'assets\README.md' file (assets being a solution folder)
3. Close VS and Restart it
4. > When VS restarts and re-opens the Readme.md file (and Markdown Editor seems to do its thing / initializing), the error above occurs 

### Current behavior
Uhm - An Error message box? "It all" (VS, markdown editing etc) does seem to work when clicking it away though.. that error message box just is a tad annoying

### Expected behavior
No Error Messagebox!

**Comment by madskristensen** [comment]
I cannot repro this issue. It might have been fixed in the latest [CI build](http://vsixgallery.com/extension/9ca64947-e9ca-4543-bfb8-6cce9be19fd6/) as a side-effect of another fix. Can you please help verify that the bug has been fixed in the CI build?

**Comment by jbattermann** [comment]
Still happening in that CI build - however I forked the repo, built the extension, ran it with debugger attached and the exception is raised in line 53 of MarkdownClassifier.cs and the problem appears to come from the 'length' parameter (the second one for new Span(...)) which is `mdobj.Span.Length` value, which in my case / my repo's Readme.md is actually **-**6556:

![span_negative_length](https://cloud.githubusercontent.com/assets/828/16598205/1143101e-42fd-11e6-962d-15ab5ea34e20.png)

.. why that is - I don't know :-/

**Comment by jbattermann** [comment]
What I noticed in the Experimental instance now though is that I had to scroll down in the Readme.md after opening it.. to trigger the Exception..

**Comment by madskristensen** [comment]
@jbattermann Wow, thanks for the extra details. Looks like the issue is with the Markdig parser. At least the extension can be made to gracefully exist so no prompt is shown.

/cc @xoofx

**Comment by jbattermann** [comment]
Sure thing :+1:

**Comment by madskristensen** [comment]
So this might be fixed in the latest [CI build](http://vsixgallery.com/extension/9ca64947-e9ca-4543-bfb8-6cce9be19fd6/) if you want to test it out?

**Comment by xoofx** [comment]
This should be fixed by [commit 354f31b8](https://github.com/lunet-io/markdig/commit/354f31b870d60db189bafe26534eb089cffaf3ff) in markdig

**Comment by jbattermann** [comment]
@madskristensen no more Exception here with the v1.4.109 build :+1:
